services:
  web:
    build: ./web
    ports: 
      - "80:80"
    depends_on:
      - api
    develop:
      watch:
        - path: ./web
          action: "rebuild"
  api:
    build: ./api
    ports: 
      - "8000:8000"
    volumes:
      - ./data:/app/data
    develop:
      watch:
        - path: ./api/main.py
          action: "rebuild"
