FROM python:3.13-bookworm

WORKDIR /app

COPY requirements.txt ./

RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt

COPY main.py ./

CMD ["fastapi", "run", "main.py", "--port", "8000", "--host", "0.0.0.0"]

EXPOSE 8000
