FROM node:23.7.0-alpine

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.npm npm install --legacy-peer-deps

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm run build

FROM nginx:1.27.4-bookworm

COPY --from=0 /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80